FROM alpine:3

LABEL author="Jution Candra Kirana"
LABEL company="PT Enigma Cipta Humanika" website="https://enigmacamp.com/"

RUN mkdir app

RUN echo "Halo ini IT Bootcamp" > app/enigmacamp.txt

CMD cat app/enigmacamp.txt